USE [BdTienda]
GO

/****** Object:  Table [dbo].[Ffactc_ecom]    Script Date: 26/03/2018 11:07:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TkActivD](
	[TIENDA] [varchar](5) NOT NULL,
	[SERIE] [varchar](4) NOT NULL,
	[NUMERO] [varchar](8) NOT NULL,
	[CODACTI] [varchar](20) NOT NULL,
	[CANT] [Int] NULL,
	[MTOUNI] [DECIMAL](18,4) NULL
 CONSTRAINT [PK_TkActivD] PRIMARY KEY CLUSTERED 
(
	[TIENDA] ASC,
	[SERIE] ASC,
	[NUMERO] ASC,
	[CODACTI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO